# Generated by Django 4.2.5 on 2023-09-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLandingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PregnantWomanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Delivery_Number', models.IntegerField()),
                ('Delivery_Time', models.IntegerField()),
                ('Blood_Of_Pressure', models.IntegerField()),
                ('Heart_Problem', models.IntegerField()),
                ('Caesarian_Predict', models.IntegerField()),
                ('Caesarian_Label_Yes', models.FloatField()),
                ('Caesarian_Label_NO', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number_user', models.CharField(max_length=100)),
                ('contry_user', models.CharField(max_length=100)),
                ('gender_user', models.CharField(max_length=100)),
            ],
        ),
    ]
