# Generated by Django 4.2.5 on 2023-09-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contry_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
